merge_to_confuturo-entrada:
  image: alpine
  before_script:
    - apk update
    - apk add curl jq
  script:
    - >
      merge_request_response=$(curl --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" --request
        POST --form "source_branch=develop" --form
        "target_branch=confuturo-entrada" --form "title=Merge develop to
        confuturo-entrada"
        "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests")
      echo "Merge Request RESPONSE: $merge_request_response"
      merge_request_id=$(echo "$merge_request_response" | jq -r '.id')
      echo "Merge Request ID: $merge_request_id"
      curl --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" --request POST
      "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests/$merge_request_id/approve"
  only:
    - develop
