stages:
  - sync
  
image: alpine
# variable:
#   - MERGE_REQUEST_RESPONSE=""
  
create_merge_request:
  stage: sync
  before_script:
    - apk update
    - apk add curl jq
  script:   
    - |
      MERGE_REQUEST_RESPONSE=$(curl --header "PRIVATE-TOKEN: ${CI_JOB_TOKEN}" \
      --request POST --form "source_branch=develop" \
      --form "target_branch=confuturo-entrada" \
      --form "title=Merge develop to confuturo-entrada" \
      "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/merge_requests")    
    - echo Merge Request RESPONSE $MERGE_REQUEST_RESPONSE
    - echo iid $CI_MERGE_REQUEST_IID    
  only:
    - develop
  tags: 
    - gcp

merge_request_gitlab:
  stage: sync
  needs: [create_merge_request]
  before_script:
    - apk update
    - apk add curl jq
  script:
    - MERGE_REQUEST_IID=$(echo "${MERGE_REQUEST_RESPONSE}" | jq -r '.iid')
    - |
      echo "Merge Request ID ${MERGE_REQUEST_IID}"
      echo curl --header "PRIVATE-TOKEN $CI_JOB_TOKEN" --request PUT "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests/$MERGE_REQUEST_IID/merge"
      MERGE=$(curl --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" --request PUT "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests/$MERGE_REQUEST_IID/merge")
      echo "Merge Finalizado $MERGE"
  only:
    - develop
  tags: 
    - gcp