merge_to_confuturo-entrada:
  image: curlimages/curl:7.85.0
  script:
    - >
      merge_request_response=$(curl --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" --resquest POST 
      --form "source_branch=develop" --form "target_branch=confuturo-entrada"
      --form "title=Merge develop to confuturo-entrada"
      "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests")
      
      merge_request_id=$(echo "$merge_request_response" | jq '.id')

      curl --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" --request POST
      "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests/$merge_request_id/approve"
  only:
    - develop
